# Generated by Django 5.0.6 on 2024-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_reg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeuser",
            name="username",
        ),
        migrations.AddField(
            model_name="customeuser",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customeuser",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
