# Generated by Django 5.0.6 on 2024-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_reg", "0002_remove_customeuser_username_customeuser_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeuser",
            name="username",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
